CREATE DATABASE IF NOT EXISTS winga_official CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE winga_official;
CREATE TABLE users (id INT PRIMARY KEY AUTO_INCREMENT,full_name VARCHAR(150) NOT NULL,shop_name VARCHAR(150),phone VARCHAR(20) UNIQUE NOT NULL,email VARCHAR(150) UNIQUE,password VARCHAR(255) NOT NULL,profile_image VARCHAR(255),role ENUM('seller','admin') DEFAULT 'seller',status ENUM('active','suspended') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE products (id INT PRIMARY KEY AUTO_INCREMENT,user_id INT NOT NULL,name VARCHAR(200) NOT NULL,brand VARCHAR(100),category ENUM('phone','laptop','computer','accessory','other') DEFAULT 'phone',unique_identifier VARCHAR(100) NOT NULL UNIQUE,identifier_type ENUM('imei','serial') NOT NULL,cost_price DECIMAL(12,2) NOT NULL,selling_price DECIMAL(12,2) NOT NULL,condition_status ENUM('new','used','refurbished') DEFAULT 'used',description TEXT,status ENUM('available','sold','returned','transferred') DEFAULT 'available',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE product_images (id INT PRIMARY KEY AUTO_INCREMENT,product_id INT NOT NULL,image_path VARCHAR(255) NOT NULL,is_primary BOOLEAN DEFAULT FALSE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE sales (id INT PRIMARY KEY AUTO_INCREMENT,product_id INT NOT NULL,seller_id INT NOT NULL,customer_name VARCHAR(150),customer_phone VARCHAR(20),selling_price DECIMAL(12,2) NOT NULL,cost_price DECIMAL(12,2) NOT NULL,profit DECIMAL(12,2) NOT NULL,payment_method ENUM('cash','mobile_money','bank','other') DEFAULT 'cash',notes TEXT,sold_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(product_id) REFERENCES products(id),FOREIGN KEY(seller_id) REFERENCES users(id));
CREATE TABLE returns (id INT PRIMARY KEY AUTO_INCREMENT,sale_id INT NOT NULL,product_id INT NOT NULL,seller_id INT NOT NULL,reason TEXT,refund_amount DECIMAL(12,2),returned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(sale_id) REFERENCES sales(id),FOREIGN KEY(product_id) REFERENCES products(id),FOREIGN KEY(seller_id) REFERENCES users(id));
CREATE TABLE product_requests (id INT PRIMARY KEY AUTO_INCREMENT,requester_id INT NOT NULL,title VARCHAR(200) NOT NULL,description TEXT,preferred_brand VARCHAR(100),preferred_model VARCHAR(150),max_budget DECIMAL(12,2),status ENUM('open','accepted','rejected','cancelled','completed') DEFAULT 'open',accepted_by INT NULL,accepted_product_id INT NULL,agreed_price DECIMAL(12,2) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(requester_id) REFERENCES users(id),FOREIGN KEY(accepted_by) REFERENCES users(id),FOREIGN KEY(accepted_product_id) REFERENCES products(id));
CREATE TABLE product_transfers (id INT PRIMARY KEY AUTO_INCREMENT,product_id INT NOT NULL,from_user_id INT NOT NULL,to_user_id INT NOT NULL,request_id INT NULL,transfer_price DECIMAL(12,2),notes TEXT,transferred_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(product_id) REFERENCES products(id),FOREIGN KEY(from_user_id) REFERENCES users(id),FOREIGN KEY(to_user_id) REFERENCES users(id),FOREIGN KEY(request_id) REFERENCES product_requests(id));
