import {NavLink,Outlet} from 'react-router-dom';
import {useState} from 'react';
import {LayoutDashboard,Package,ShoppingCart,Undo2,ArrowLeftRight,BarChart3,LogOut,Settings,Shield,Users,Search,Menu,X,SlidersHorizontal} from 'lucide-react';
import {useAuth} from '../../context/AuthContext';
import {imageUrl} from '../../utils/branding';

const seller=[['/',LayoutDashboard,'Dashboard'],['/products',Package,'Products'],['/sales',ShoppingCart,'Sales'],['/customers',Users,'Customers'],['/returns',Undo2,'Returns'],['/requests',ArrowLeftRight,'Requests'],['/expenses',ShoppingCart,'Expenses'],['/reports',BarChart3,'Reports']];
function Brand({user}){return <span className="flex items-center gap-3">{user?.profile_image?<img src={imageUrl(user.profile_image)} alt="Shop logo" className="h-10 w-10 rounded-xl bg-white object-contain p-1"/>:<span className="grid h-10 w-10 place-items-center rounded-xl bg-orange-500 font-black text-white">E</span>}<span><b className="block text-lg leading-tight">{user?.shop_name||'EMS'}</b><small className="text-[9px] font-semibold tracking-widest text-orange-200">ELECTRONIC MANAGEMENT SYSTEM</small></span></span>}
export default function Layout(){const {user,signOut}=useAuth(),[open,setOpen]=useState(false);const links=user?.role==='admin'?[['/admin',Shield,'Administration'],['/users',Users,'Users'],['/admin-settings',SlidersHorizontal,'Settings'],['/account',Settings,'Account']]:[...seller,['/account',Settings,'Account']];const nav=<>{links.map(([to,I,l])=><NavLink onClick={()=>setOpen(false)} end={to==='/'} key={to} to={to} className={({isActive})=>`mb-1 flex items-center gap-3 rounded-xl px-3 py-2.5 ${isActive?'bg-orange-500 text-white shadow-lg shadow-orange-950/20':'text-orange-50/80 hover:bg-white/10 hover:text-white'}`}><I size={18}/>{l}</NavLink>)}<button onClick={signOut} className="mt-4 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-orange-200 hover:bg-white/10"><LogOut size={18}/>Log out</button></>;return <div className="min-h-screen md:flex"><header className="m-3 flex items-center justify-between rounded-2xl bg-ems-900 p-4 text-white shadow-lg md:hidden"><Brand user={user}/><button className="grid h-11 w-11 place-items-center rounded-xl hover:bg-white/10" aria-label={open?'Close navigation menu':'Open navigation menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X size={24}/>:<Menu size={24}/>}</button></header>{open&&<div className="absolute left-3 right-3 top-20 z-50 rounded-2xl bg-ems-900 p-3 text-white shadow-xl md:hidden">{nav}</div>}<aside className="hidden min-h-screen bg-ems-900 p-5 text-white md:block md:w-72"><div className="mb-10 border-b border-white/10 pb-5"><Brand user={user}/></div><nav>{nav}</nav><div className="mt-10 rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-sm font-bold">{user?.shop_name||user?.full_name}</p><p className="mt-1 text-xs text-orange-200/80">{user?.role==='admin'?'Administrator':'Shop workspace'}</p></div></aside><main className="mx-auto max-w-7xl flex-1 p-4 md:p-8"><Outlet/></main></div>}

