import {useEffect,useRef,useState} from 'react';
import {useAuth} from '../context/AuthContext';
import api from '../services/api';
import {imageUrl} from '../utils/branding';
import {CreditCard,Upload} from 'lucide-react';
import {prepareImage} from '../utils/prepareImage';
import UploadOverlay from '../components/common/UploadOverlay';

const PAYMENT_NUMBER='0628115130';
const PAYMENT_NAME='Emmanuel Charles';
const MONTHLY_FEE=10000;
export default function Account(){
  const {user,refreshUser}=useAuth();
  const [profile,setProfile]=useState({full_name:user?.full_name||'',shop_name:user?.shop_name||'',phone:user?.phone||'',email:user?.email||''});
  const [password,setPassword]=useState({current_password:'',new_password:''});
  const [message,setMessage]=useState(''),[error,setError]=useState(''),[paymentOpen,setPaymentOpen]=useState(false),[uploading,setUploading]=useState(false),[logoPreview,setLogoPreview]=useState('');
  const logoInput=useRef(null);
  useEffect(()=>()=>{if(logoPreview)URL.revokeObjectURL(logoPreview)},[logoPreview]);
  const submit=async(path,data)=>{try{setError('');setMessage('');const result=await api.post(path,data);setMessage(result.message||'Changes saved.');if(path==='/auth/profile.php')await refreshUser()}catch(e){setError(e.message)}};
  const uploadLogo=async event=>{const file=event.target.files?.[0];if(!file)return;setLogoPreview(URL.createObjectURL(file));setUploading(true);setError('');setMessage('');try{const normalized=await prepareImage(file);const form=new FormData();form.append('logo',normalized,normalized.name);const result=await api.post('/auth/upload-logo.php',form);await refreshUser();setLogoPreview('');setMessage(result.message)}catch(e){setError(e.message)}finally{setUploading(false);event.target.value=''}};
  const receiptText=encodeURIComponent(`Hello, I have paid TZS ${MONTHLY_FEE.toLocaleString()} for my EMS monthly subscription using HaloPesa ${PAYMENT_NUMBER}. I am sending my payment receipt. Shop: ${user?.shop_name||user?.full_name}.`);
  return <div className="max-w-2xl">
    <h2 className="mb-5 text-3xl font-bold">Account</h2>
    {user?.role!=='admin'&&<section className="card mb-5 border border-orange-100 bg-gradient-to-br from-white to-orange-50"><div className="flex items-center gap-3"><span className="rounded-xl bg-orange-100 p-3 text-orange-700"><CreditCard/></span><div><h3 className="font-bold">Subscription</h3><p className="text-sm text-slate-500">{user?.days_remaining??0} days remaining · Access ends {user?.subscription_end_at||user?.trial_ends_at||'—'}</p></div></div><button className="btn-primary mt-4" onClick={()=>setPaymentOpen(true)}>View payment instructions</button></section>}
    {message&&<p role="status" className="mb-3 rounded-xl bg-green-50 p-3 text-green-700">{message}</p>}
    {error&&<p role="alert" className="mb-3 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}
    <form className="card mb-5" onSubmit={e=>{e.preventDefault();submit('/auth/profile.php',profile)}}><h3 className="mb-3 font-bold">Shop profile</h3>{[['full_name','Seller name'],['shop_name','Shop name'],['phone','Contact phone'],['email','Email']].map(([key,label])=><div className="mt-2" key={key}><label className="label">{label}</label><input required={key==='full_name'||key==='phone'} type={key==='email'?'email':'text'} value={profile[key]} onChange={e=>setProfile({...profile,[key]:e.target.value})}/></div>)}<button className="btn-primary mt-4">Save shop details</button></form>
    <section className="card mb-5"><h3 className="mb-1 font-bold">Shop logo</h3><p className="mb-4 text-sm text-slate-500">Shown in the app, reports and warranty certificates.</p><div className="flex flex-wrap items-center gap-4">{logoPreview||user?.profile_image?<img src={logoPreview||imageUrl(user.profile_image)} alt="Shop logo preview" className="h-20 w-20 rounded-2xl border border-slate-200 bg-white object-contain p-2"/>:<div className="grid h-20 w-20 place-items-center rounded-2xl bg-orange-100 text-2xl font-black text-orange-800">{(user?.shop_name||'S').slice(0,1).toUpperCase()}</div>}<div><input ref={logoInput} type="file" accept="image/*" className="hidden" onChange={uploadLogo}/><button type="button" disabled={uploading} onClick={()=>logoInput.current?.click()} className="btn-secondary inline-flex items-center gap-2"><Upload size={16}/>Upload logo</button><p className="mt-2 text-xs text-slate-400">JPG, PNG, WebP, or a phone image converted before upload.</p></div></div></section>
    <form className="card" onSubmit={e=>{e.preventDefault();submit('/auth/change-password.php',password);setPassword({current_password:'',new_password:''})}}><h3 className="mb-3 font-bold">Change password</h3><label className="label">Current password</label><input required type="password" autoComplete="current-password" value={password.current_password} onChange={e=>setPassword({...password,current_password:e.target.value})}/><label className="label mt-3">New password</label><input required minLength="6" type="password" autoComplete="new-password" value={password.new_password} onChange={e=>setPassword({...password,new_password:e.target.value})}/><button className="btn-primary mt-4">Update password</button></form>
    {paymentOpen&&<div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/65 p-4" onClick={()=>setPaymentOpen(false)}><section className="card w-full max-w-lg" onClick={e=>e.stopPropagation()}><h3 className="text-2xl font-black">Monthly subscription payment</h3><p className="mt-2 text-slate-600">Pay by HaloPesa, then send your payment receipt to support on WhatsApp.</p><div className="my-5 space-y-3 rounded-2xl bg-orange-50 p-4"><div className="flex justify-between gap-4"><span className="text-slate-600">Monthly amount</span><b>TZS {MONTHLY_FEE.toLocaleString()}</b></div><div className="flex justify-between gap-4"><span className="text-slate-600">Payment method</span><b>HaloPesa</b></div><div className="flex justify-between gap-4"><span className="text-slate-600">Payment number</span><b>{PAYMENT_NUMBER}</b></div><div className="flex justify-between gap-4"><span className="text-slate-600">Account name</span><b>{PAYMENT_NAME}</b></div></div><p className="mb-4 text-sm text-slate-500">After paying TZS {MONTHLY_FEE.toLocaleString()}, use the button below to open WhatsApp and attach your receipt. Include your shop name so the payment can be matched to your account.</p><div className="flex flex-wrap gap-2"><a className="btn-primary" href={`https://wa.me/${String(user?.payment_whatsapp||'').replace(/\D/g,'')}?text=${receiptText}`} target="_blank" rel="noreferrer">Send receipt on WhatsApp</a><button type="button" className="btn-secondary" onClick={()=>setPaymentOpen(false)}>Cancel</button></div></section></div>}
    {uploading&&<UploadOverlay label="Preparing and uploading shop image..."/>}
  </div>;
}
