import {useEffect,useState} from 'react';
import {Eye,FileBadge,Filter} from 'lucide-react';
import api from '../services/api';
import {imageUrl} from '../utils/branding';
import WarrantyCertificate from '../components/common/WarrantyCertificate';

const money=value=>Number(value||0).toLocaleString();
const conditions=[['new','Full box'],['used','Used Dubai'],['refurbished','Used Bongo']];
export default function Customers(){
  const [query,setQuery]=useState(''),[rows,setRows]=useState([]),[filtersOpen,setFiltersOpen]=useState(false),[minimum,setMinimum]=useState(''),[maximum,setMaximum]=useState(''),[condition,setCondition]=useState(''),[returned,setReturned]=useState(''),[warranty,setWarranty]=useState(''),[detail,setDetail]=useState(null),[certificate,setCertificate]=useState(null);
  useEffect(()=>{const timer=setTimeout(()=>api.get('/customers/list.php',{params:{q:query}}).then(result=>setRows(result.customers)),200);return()=>clearTimeout(timer)},[query]);
  const purchases=rows.filter(row=>(!minimum||Number(row.selling_price)>=Number(minimum))&&(!maximum||Number(row.selling_price)<=Number(maximum))&&(!condition||row.condition_status===condition)&&(!returned||(returned==='yes'?!!row.return_id:!row.return_id))&&(!warranty||(warranty==='valid'?row.warranty_valid:!row.warranty_valid)));
  return <>
    <h2 className="mb-4 text-3xl font-bold">Customers</h2>
    <div className="flex gap-2"><input placeholder="Search customer name, contact or product" value={query} onChange={e=>setQuery(e.target.value)}/><button className="btn-secondary inline-flex items-center gap-2" onClick={()=>setFiltersOpen(!filtersOpen)}><Filter size={16}/>Filter</button></div>
    {filtersOpen&&<div className="card mt-2 grid gap-2 sm:grid-cols-2"><input type="number" placeholder="Minimum price" value={minimum} onChange={e=>setMinimum(e.target.value)}/><input type="number" placeholder="Maximum price" value={maximum} onChange={e=>setMaximum(e.target.value)}/><select value={condition} onChange={e=>setCondition(e.target.value)}><option value="">All product conditions</option>{conditions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select value={returned} onChange={e=>setReturned(e.target.value)}><option value="">All return statuses</option><option value="yes">Returned</option><option value="no">Not returned</option></select><select value={warranty} onChange={e=>setWarranty(e.target.value)}><option value="">All warranty statuses</option><option value="valid">Warranty valid</option><option value="expired">Expired / no warranty</option></select></div>}
    <div className="mt-4 grid gap-3">{purchases.map(row=><article className="card" key={row.id}>
      <div className="flex flex-wrap items-start justify-between gap-3"><button className="min-w-0 flex-1 text-left" onClick={()=>setDetail(row)}><b>{row.customer_name||'Walk-in customer'}</b><p className="text-slate-500">{row.customer_phone||'No contact'} · {row.name}</p><p className="text-sm">{row.shop_name||row.seller_name} · TZS {money(row.selling_price)}</p><p className="text-xs text-slate-500">{row.sold_at}</p></button><span className={`rounded-full px-3 py-1 text-xs font-bold ${row.warranty_valid?'bg-green-100 text-green-800':'bg-slate-100 text-slate-600'}`}>{row.warranty_valid?'Warranty active':row.warranty_months?'Warranty expired':'No warranty'}</span></div>
      <div className="mt-3 flex flex-wrap gap-2"><button className="btn-secondary inline-flex items-center gap-2 text-sm" onClick={()=>setDetail(row)}><Eye size={15}/>Purchase details</button>{Number(row.warranty_months)>0&&<button className="btn-primary inline-flex items-center gap-2 text-sm" onClick={()=>setCertificate(row)}><FileBadge size={15}/>Preview / download warranty card</button>}</div>
    </article>)}</div>
    {detail&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" onClick={()=>setDetail(null)}><div className="card max-h-[90vh] w-full max-w-lg overflow-auto" onClick={e=>e.stopPropagation()}><button className="btn-secondary float-right" onClick={()=>setDetail(null)}>Close</button><h3 className="text-2xl font-bold">Customer purchase</h3><p className="mt-3"><b>{detail.customer_name||'Walk-in customer'}</b><br/>{detail.customer_phone||'No contact'}</p><div className="mt-4 border-t pt-3">{detail.images?.[0]&&<img className="mb-3 h-48 w-full rounded-xl object-cover" src={imageUrl(detail.images[0].image_path)} alt={detail.name}/>}<b>{detail.name}</b><p>{detail.brand||'—'} · {detail.category}</p><p>Condition: {conditions.find(([value])=>value===detail.condition_status)?.[1]||detail.condition_status}</p><p>IMEI / Serial: {detail.unique_identifier}</p><p>Price: TZS {money(detail.selling_price)}</p><p>Sold: {detail.sold_at}</p></div><div className="mt-4 rounded-xl bg-orange-50 p-4"><h4 className="font-bold">Warranty details</h4><p>Duration: {detail.warranty_months} month(s)</p><p>Expires: {detail.warranty_ends_at||'No warranty'}</p><p>Status: <b className={detail.warranty_valid?'text-green-700':'text-red-700'}>{detail.warranty_valid?'Valid':'Expired / not covered'}</b></p><p>Shop: {detail.shop_name||detail.seller_name}</p><p>Seller: {detail.seller_name} · {detail.seller_phone}</p>{Number(detail.warranty_months)>0&&<button className="btn-primary mt-3 inline-flex items-center gap-2" onClick={()=>{setCertificate(detail);setDetail(null)}}><FileBadge size={15}/>Preview / download warranty card</button>}</div>{detail.return_id&&<div className="mt-3 rounded-xl bg-red-50 p-3"><b>Returned product</b><p>Date: {detail.returned_at}</p><p>Reason: {detail.reason||'Not recorded'}</p><p>Refund: TZS {money(detail.refund_amount)}</p></div>}</div></div>}
    {certificate&&<WarrantyCertificate purchase={certificate} onClose={()=>setCertificate(null)}/>}
  </>;
}
