import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight,Boxes,ChartNoAxesCombined,Clock3,PackagePlus,ShoppingBag,Wallet} from 'lucide-react';
import api from '../services/api';
import {useAuth} from '../context/AuthContext';

const cards=[['available_stock','Available stock',Boxes,'items'],['today_sales',"Today's sales",ShoppingBag,'sales'],['today_profit',"Today's profit",Wallet,'TZS'],['pending_requests','Open requests',Clock3,'requests'],['stock_value','Stock value',ChartNoAxesCombined,'TZS']];
const cash=v=>Number(v||0).toLocaleString('en-US',{maximumFractionDigits:0});
function MiniBarChart({values}){const max=Math.max(...values.map(x=>x.value),1);return <div className="mt-5 flex h-44 items-end gap-2 border-b border-slate-100 pb-2">{values.map((x,i)=><div className="group flex h-full flex-1 flex-col items-center justify-end gap-2" key={x.label}><div title={`${x.label}: ${cash(x.value)}`} className="w-full max-w-10 rounded-t-lg bg-gradient-to-t from-orange-700 to-orange-400 transition hover:from-orange-600" style={{height:`${Math.max(6,x.value/max*100)}%`}}/><span className="text-[10px] text-slate-400">{x.label}</span></div>)}</div>}
function DonutChart({available,sold}){const total=available+sold,share=total?sold/total*100:0;return <div className="flex items-center gap-5"><div className="relative h-32 w-32 shrink-0 rounded-full" style={{background:`conic-gradient(#f97316 0% ${share}%, #e2e8f0 ${share}% 100%)`}}><div className="absolute inset-4 grid place-items-center rounded-full bg-white text-center"><div><b className="block text-2xl">{total}</b><span className="text-xs text-slate-500">tracked</span></div></div></div><div className="space-y-3 text-sm"><p className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-orange-500"/>Sold <b>{sold}</b></p><p className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-slate-200"/>Available <b>{available}</b></p></div></div>}
export default function Dashboard(){const [s,setS]=useState({}),{user}=useAuth();useEffect(()=>{const load=()=>api.get('/dashboard/stats.php').then(r=>setS(r.stats));load();const t=setInterval(load,9000);return()=>clearInterval(t)},[]);const trend=useMemo(()=>s.sales_trend||[],[s.sales_trend]);return <><div className="mb-7 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-orange-600">{user?.shop_name||'Your shop'}</p><h2 className="mt-1 text-3xl font-black tracking-tight">Dashboard</h2><p className="mt-1 text-slate-500">A live overview of your shop performance.</p></div><Link className="btn-primary inline-flex items-center gap-2" to="/sales"><PackagePlus size={17}/> Record sale</Link></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([k,l,I,unit])=><div className="card overflow-hidden" key={k}><div className="flex items-start justify-between"><p className="text-sm text-slate-500">{l}</p><span className="rounded-xl bg-orange-50 p-2 text-orange-600"><I size={19}/></span></div><b className="mt-4 block text-2xl font-black">{unit==='TZS'?`TZS ${cash(s[k])}`:`${s[k]||0} ${unit}`}</b><p className="mt-1 text-xs text-slate-400">{k==='today_sales'?'Completed today':k==='today_profit'?'Net of recorded returns':k==='available_stock'?'Ready to sell':k==='pending_requests'?'Awaiting action':'Available stock cost'}</p></div>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-[1.5fr_1fr]"><section className="card"><div className="flex items-center justify-between"><div><h3 className="text-lg font-bold">Sales performance</h3><p className="text-sm text-slate-500">Revenue for the last 7 days</p></div><Link to="/reports" className="text-sm font-semibold text-orange-700">View report <ArrowUpRight className="inline" size={16}/></Link></div>{trend.length?<MiniBarChart values={trend}/>:<p className="mt-8 rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-500">Sales history will appear here after you record sales.</p>}</section><section className="card"><h3 className="text-lg font-bold">Inventory mix</h3><p className="mb-5 text-sm text-slate-500">Available and sold products</p><DonutChart available={Number(s.available_stock||0)} sold={Number(s.sold_stock||0)}/><Link to="/products" className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-orange-700">Manage products <ArrowUpRight size={16}/></Link></section></div><p className="mt-4 text-xs text-slate-400">Dashboard refreshes automatically every 9 seconds.</p></>}
