import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {BadgeCheck,Trash2} from 'lucide-react';
import {deleteProduct,products,updateProduct} from '../services/productService';
import {imageUrl} from '../utils/branding';

const cash=value=>Number(value||0).toLocaleString();
const conditions=[['new','Full box'],['used','Used Dubai'],['refurbished','Used Bongo']];
const conditionName=value=>conditions.find(([key])=>key===value)?.[1]||value||'—';
export default function Products(){
  const [rows,setRows]=useState([]),[filters,setFilters]=useState({q:'',status:'',brand:''}),[showFilters,setShowFilters]=useState(false),[detail,setDetail]=useState(null),[zoom,setZoom]=useState(null),[edit,setEdit]=useState(null),[error,setError]=useState('');
  const load=()=>products(filters).then(result=>setRows(result.products)).catch(e=>setError(e.message));
  useEffect(()=>{const timer=setTimeout(load,200);return()=>clearTimeout(timer)},[filters]);
  const remove=async product=>{if(!window.confirm(`Delete ${product.name} from your inventory?`))return;try{await deleteProduct(product.id);load()}catch(e){setError(e.message)}};
  const save=async event=>{event.preventDefault();if(!window.confirm('Save these product changes?'))return;try{await updateProduct(edit);setEdit(null);load()}catch(e){setError(e.message)}};
  return <>
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="text-3xl font-bold">Products</h2><Link className="btn-primary" to="/products/new">Add product</Link></div>
    {error&&<p role="alert" className="mb-3 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}
    <div className="mb-3 flex gap-2"><input autoFocus placeholder="Search products, brand, IMEI or serial" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/><button className="btn-secondary" onClick={()=>setShowFilters(!showFilters)}>Filter</button></div>
    {showFilters&&<div className="card mb-4 grid gap-2 sm:grid-cols-2"><select aria-label="Filter products by status" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All products</option><option value="available">Available</option><option value="sold">Sold</option><option value="returned">Returned</option><option value="transferred">Transferred</option></select><input aria-label="Filter products by brand" placeholder="Brand" value={filters.brand} onChange={e=>setFilters({...filters,brand:e.target.value})}/></div>}
    <div className="grid gap-3">{rows.map(product=><article className="card flex flex-wrap items-center justify-between gap-3" key={product.id}>
      <button className="flex min-w-0 flex-1 items-center gap-3 text-left" onClick={()=>setDetail(product)}>{product.images?.[0]&&<img className="h-16 w-16 shrink-0 rounded-xl object-cover" src={imageUrl(product.images[0].image_path)} alt={product.name}/>}<span className="min-w-0"><b className="block truncate">{product.name}</b><span className="block text-sm text-slate-500">{product.brand||'—'} · {product.unique_identifier} · TZS {cash(product.selling_price)}</span><span className="block text-xs text-slate-500">{conditionName(product.condition_status)} · {product.status}</span>{(product.return_details||product.status==='returned')&&<span className="mt-1 inline-flex items-center gap-1 rounded-full bg-orange-100 px-2.5 py-1 text-xs font-bold text-orange-900"><BadgeCheck size={13}/>Returned</span>}</span></button>
      <div className="flex gap-2">{product.status!=='transferred'&&<><button className="btn-secondary text-sm" onClick={()=>setEdit({...product})}>Edit</button><button aria-label={`Delete ${product.name}`} className="rounded-xl bg-red-50 p-2.5 text-red-700 hover:bg-red-100" onClick={()=>remove(product)}><Trash2 size={17}/>Delete</button></>}</div>
    </article>)}</div>
    {detail&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" onClick={()=>setDetail(null)}><div className="card max-h-[90vh] w-full max-w-2xl overflow-auto" onClick={e=>e.stopPropagation()}><button className="float-right btn-secondary" onClick={()=>setDetail(null)}>Close</button><div className="flex items-center gap-3"><h3 className="text-2xl font-bold">{detail.name}</h3>{(detail.return_details||detail.status==='returned')&&<span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-bold text-orange-900">Returned</span>}</div><div className="my-4 flex flex-wrap gap-2">{detail.images?.map(image=><img onClick={()=>setZoom(imageUrl(image.image_path))} className="h-32 w-32 cursor-zoom-in rounded-xl object-cover" key={image.id} src={imageUrl(image.image_path)} alt={detail.name}/>)}</div><p><b>IMEI / Serial:</b> {detail.unique_identifier}</p><p><b>Brand:</b> {detail.brand||'—'} · <b>Condition:</b> {conditionName(detail.condition_status)}</p><p><b>Cost:</b> TZS {cash(detail.cost_price)} · <b>Selling price:</b> TZS {cash(detail.selling_price)}</p><p><b>Stock status:</b> {detail.status}</p><p className="mt-3 whitespace-pre-wrap">{detail.description||'No description provided.'}</p>{detail.sale_details&&<div className="mt-4 rounded-xl bg-orange-50 p-3"><b>Sale details</b><p>Customer: {detail.sale_details.customer_name||'Walk-in customer'}</p><p>Contact: {detail.sale_details.customer_phone||'Not recorded'}</p><p>Sold: {detail.sale_details.sold_at}</p></div>}{detail.return_details&&<div className="mt-4 rounded-xl bg-orange-50 p-3"><b>Return details</b><p>Date: {detail.return_details.returned_at}</p><p>Reason: {detail.return_details.reason||'Not recorded'}</p><p>Refund: TZS {cash(detail.return_details.refund_amount)}</p></div>}{detail.transfer_details&&<div className="mt-4 rounded-xl bg-sky-50 p-3"><b>Transfer details</b><p>From: {detail.transfer_details.from_shop||'Shop'} ? To: {detail.transfer_details.to_shop||'Shop'}</p><p>Date: {detail.transfer_details.transferred_at}</p></div>}</div></div>}
    {zoom&&<div className="fixed inset-0 z-[60] grid place-items-center bg-black/80 p-4" onClick={()=>setZoom(null)}><img className="max-h-full max-w-full object-contain" src={zoom} alt="Zoomed product"/></div>}
    {edit&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><form className="card w-full max-w-xl" onSubmit={save}><h3 className="text-xl font-bold">Edit product</h3>{[['name','Name'],['brand','Brand'],['cost_price','Cost price'],['selling_price','Selling price']].map(([key,label])=><label className="label mt-3" key={key}>{label}<input className="mt-1" type={key.includes('price')?'number':'text'} value={edit[key]||''} onChange={e=>setEdit({...edit,[key]:e.target.value})}/></label>)}<label className="label mt-3">Condition<select className="mt-1" value={edit.condition_status} onChange={e=>setEdit({...edit,condition_status:e.target.value})}>{conditions.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><button className="btn-primary mt-4">Save changes</button><button type="button" className="btn-secondary ml-2" onClick={()=>setEdit(null)}>Cancel</button></form></div>}
  </>;
}
