import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {BadgeCheck,Trash2,LoaderCircle} from 'lucide-react';
import {deleteProduct,products,updateProduct,uploadImages} from '../services/productService';
import {imageUrl} from '../utils/branding';
const cash=value=>Number(value||0).toLocaleString();
const conditions=[['new','Full box'],['used','Used Dubai'],['refurbished','Used Bongo']];
const categories=['phone','laptop','computer','accessory','other'];
const conditionName=value=>conditions.find(([key])=>key===value)?.[1]||value||'';
export default function Products(){
 const [rows,setRows]=useState([]),[filters,setFilters]=useState({q:'',status:'',brand:''}),[showFilters,setShowFilters]=useState(false),[detail,setDetail]=useState(null),[zoom,setZoom]=useState(null),[edit,setEdit]=useState(null),[newFiles,setNewFiles]=useState([]),[removeIds,setRemoveIds]=useState([]),[error,setError]=useState(''),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false);
 const load=()=>products(filters).then(result=>setRows(result.products)).catch(e=>setError(e.message));
 useEffect(()=>{const timer=setTimeout(load,200);return()=>clearTimeout(timer)},[filters]);
 const remove=async product=>{if(!window.confirm(`Delete ${product.name} from your inventory? This cannot be undone.`))return;try{await deleteProduct(product.id);load()}catch(e){setError(e.message)}};
 const openEdit=product=>{setEdit({...product});setNewFiles([]);setRemoveIds([]);setError('')};
 const save=async event=>{event.preventDefault();if(!window.confirm(`Save changes to ${edit.name}?`))return;setSaving(true);setError('');try{await updateProduct({...edit,remove_image_ids:removeIds});if(newFiles.length){setUploading(true);await uploadImages(edit.id,newFiles)}await load();setEdit(null)}catch(e){setError(e.message)}finally{setSaving(false);setUploading(false)}};
 const field=(key,label,type='text')=><label className="label mt-3" key={key}>{label}<input required={['name','cost_price','selling_price'].includes(key)} className="mt-1" type={type} min={type==='number'?'0':undefined} step={type==='number'?'0.01':undefined} value={edit[key]??''} onChange={e=>setEdit({...edit,[key]:e.target.value})}/></label>;
 return <>
  <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="text-3xl font-bold">Products</h2><Link className="btn-primary" to="/products/new">Add product</Link></div>
  {error&&!edit&&<p role="alert" className="mb-3 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}
  <div className="mb-3 flex gap-2"><input autoFocus placeholder="Search products, brand, IMEI or serial" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/><button className="btn-secondary" onClick={()=>setShowFilters(!showFilters)}>Filter</button></div>
  {showFilters&&<div className="card mb-4 grid gap-2 sm:grid-cols-2"><select aria-label="Filter products by status" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All products</option><option value="available">Available</option><option value="sold">Sold</option><option value="returned">Returned</option><option value="transferred">Transferred</option></select><input aria-label="Filter products by brand" placeholder="Brand" value={filters.brand} onChange={e=>setFilters({...filters,brand:e.target.value})}/></div>}
  <div className="grid gap-3">{rows.map(product=><article className="card flex flex-wrap items-center justify-between gap-3" key={product.id}>
   <button className="flex min-w-0 flex-1 items-center gap-3 text-left" onClick={()=>setDetail(product)}>{product.images?.[0]?<img className="h-16 w-16 shrink-0 rounded-xl object-cover" src={imageUrl(product.images[0].image_path)} alt={product.name}/>:<span className="grid h-16 w-16 shrink-0 place-items-center rounded-xl bg-slate-100 text-xs text-slate-400">No image</span>}<span className="min-w-0"><b className="block truncate">{product.name}</b><span className="block text-sm text-slate-500">{product.brand||'Not specified'} | {product.unique_identifier} | TZS {cash(product.selling_price)}</span><span className="block text-xs text-slate-500">{conditionName(product.condition_status)} | {product.status}</span>{product.status==='sold'&&<span className="mt-1 inline-flex rounded-full bg-red-100 px-2.5 py-1 text-xs font-bold text-red-800">Sold</span>}{(product.return_details||product.status==='returned')&&<span className="mt-1 inline-flex items-center gap-1 rounded-full bg-orange-100 px-2.5 py-1 text-xs font-bold text-orange-900"><BadgeCheck size={13}/>Returned</span>}</span></button>
   <div className="flex gap-2">{product.status!=='transferred'&&<><button className="btn-secondary text-sm" onClick={()=>openEdit(product)}>Edit</button><button aria-label={`Delete ${product.name}`} className="inline-flex items-center gap-1 rounded-xl bg-red-50 p-2.5 text-red-700 hover:bg-red-100" onClick={()=>remove(product)}><Trash2 size={17}/>Delete</button></>}</div>
  </article>)}</div>
  {detail&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" onClick={()=>setDetail(null)}><div className="card max-h-[90vh] w-full max-w-2xl overflow-auto" onClick={e=>e.stopPropagation()}><button className="float-right btn-secondary" onClick={()=>setDetail(null)}>Close</button><div className="flex items-center gap-3"><h3 className="text-2xl font-bold">{detail.name}</h3>{detail.status==='sold'&&<span className="rounded-full bg-red-100 px-3 py-1 text-xs font-bold text-red-800">Sold</span>}{(detail.return_details||detail.status==='returned')&&<span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-bold text-orange-900">Returned</span>}</div><div className="my-4 flex flex-wrap gap-2">{detail.images?.map(image=><img onClick={()=>setZoom(imageUrl(image.image_path))} className="h-32 w-32 cursor-zoom-in rounded-xl object-cover" key={image.id} src={imageUrl(image.image_path)} alt={detail.name}/>)}</div><p><b>IMEI / Serial:</b> {detail.unique_identifier}</p><p><b>Brand:</b> {detail.brand||'Not specified'} | <b>Condition:</b> {conditionName(detail.condition_status)}</p><p><b>Cost:</b> TZS {cash(detail.cost_price)} | <b>Selling price:</b> TZS {cash(detail.selling_price)}</p><p><b>Stock status:</b> {detail.status}</p><p className="mt-3 whitespace-pre-wrap">{detail.description||'No description provided.'}</p>{detail.sale_details&&<div className="mt-4 rounded-xl bg-orange-50 p-3"><b>Sale details</b><p>Customer: {detail.sale_details.customer_name||'Walk-in customer'}</p><p>Contact: {detail.sale_details.customer_phone||'Not recorded'}</p><p>Sold: {detail.sale_details.sold_at}</p></div>}{detail.return_details&&<div className="mt-4 rounded-xl bg-orange-50 p-3"><b>Return details</b><p>Date: {detail.return_details.returned_at}</p><p>Reason: {detail.return_details.reason||'Not recorded'}</p><p>Refund: TZS {cash(detail.return_details.refund_amount)}</p></div>}{detail.transfer_details&&<div className="mt-4 rounded-xl bg-sky-50 p-3"><b>Transfer details</b><p>From: {detail.transfer_details.from_shop||'Shop'} | To: {detail.transfer_details.to_shop||'Shop'}</p><p>Date: {detail.transfer_details.transferred_at}</p></div>}</div></div>}
  {zoom&&<div className="fixed inset-0 z-[60] grid place-items-center bg-black/80 p-4" onClick={()=>setZoom(null)}><img className="max-h-full max-w-full object-contain" src={zoom} alt="Zoomed product"/></div>}
  {edit&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><form className="card max-h-[92vh] w-full max-w-2xl overflow-auto" onSubmit={save}><h3 className="text-xl font-bold">Edit product</h3><p className="text-sm text-slate-500">IMEI / serial is locked to preserve the product identity.</p>{error&&<p role="alert" className="mt-2 rounded bg-red-50 p-2 text-red-700">{error}</p>}{field('name','Product name')}{field('brand','Brand')}{field('cost_price','Cost price','number')}{field('selling_price','Selling price','number')}<label className="label mt-3">Category<select className="mt-1" value={edit.category||'phone'} onChange={e=>setEdit({...edit,category:e.target.value})}>{categories.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label className="label mt-3">Condition<select className="mt-1" value={edit.condition_status||'used'} onChange={e=>setEdit({...edit,condition_status:e.target.value})}>{conditions.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="label mt-3">Description<textarea className="mt-1" rows="4" value={edit.description||''} onChange={e=>setEdit({...edit,description:e.target.value})}/></label><div className="mt-4"><p className="label">Current images</p><div className="flex flex-wrap gap-3">{(edit.images||[]).filter(x=>!removeIds.includes(x.id)).map(image=><div className="relative" key={image.id}><img className="h-24 w-24 rounded-xl object-cover" src={imageUrl(image.image_path)} alt="Product"/><button type="button" className="absolute -right-2 -top-2 rounded-full bg-red-600 px-2 py-1 text-xs text-white" onClick={()=>setRemoveIds([...removeIds,image.id])}>Remove</button></div>)}{!edit.images?.length&&<p className="text-sm text-slate-500">No saved images.</p>}</div></div><label className="label mt-4">Add images<input className="mt-1" type="file" accept="image/*" multiple onChange={e=>setNewFiles([...e.target.files])}/></label>{newFiles.map(x=><p className="text-xs text-slate-500" key={x.name}>{x.name}</p>)}{saving&&<p role="status" className="mt-3 flex items-center gap-2 text-sm text-orange-700"><LoaderCircle className="animate-spin" size={18}/>{uploading?'Uploading images...':'Saving product...'}</p>}<div className="mt-4 flex gap-2"><button disabled={saving} className="btn-primary">Save changes</button><button type="button" disabled={saving} className="btn-secondary" onClick={()=>setEdit(null)}>Cancel</button></div></form></div>}
 </>;
}
